services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desi-plaza-frontend
    restart: always
    ports:
      - "8080:80"
    environment:
      VITE_API_BASE_URL: https://api.desiplazacaterings.com
    networks:
      - desi-plaza-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  desi-plaza-network:
    driver: bridge
